[package]
name = "nexers"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
bitflags = "1"
byteorder = "1"
cast = "0.2"
cesu8 = "1"
failure = "0.1"
hex = "0.3"
maplit = "1"

[profile.release]
lto = true
